name: Python linters

on:
  push:
  pull_request:

jobs:
  flake8:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install Flake8
      run: |
        pip install flake8
    - name: Run Flake8
      uses: suo/flake8-github-action@releases/v1
      with:
        checkName: 'flake8'  # NOTE: this needs to be the same as the job name.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  mypy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install MyPy
      run: |
        pip install mypy
    - name: Install Delocate dependencies.
      run: |
        pip install pytest
        python setup.py develop
    - uses: kolonialno/mypy-action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        max-errors: 0
        paths: delocate
